#!/bin/bash

proxy_apt(){
	if [[ "$1" == "-l" ]];then
		prox_apt="Acquire::http::Proxy"''' "http://192.168.43.'''$2''':8080";'''
		echo $prox_apt > /etc/apt/apt.conf && cat /etc/apt/apt.conf
	else
		prox_apt="Acquire::http::Proxy"''' "http://'''$1''':8080";'''
		echo $prox_apt > /etc/apt/apt.conf && cat /etc/apt/apt.conf
	fi
}
proxy_mvn(){
	if [[ "$1" == "-l" ]];then
		prox_mvn="<settings>\n\t<proxies>\n\t\t<proxy>\n\t\t\t<id>NetFree</id>\n\t\t\t<active>true</active>\n\t\t\t<protocol>http</protocol>\n\t\t\t<host>192.168.43.$2</host>\n\t\t\t<port>8080</port>\n\t\t</proxy>\n\t</proxies>\n</settings>"
		echo -e $prox_mvn > .m2/settings.xml && cat .m2/settings.xml
	else
		prox_mvn="<settings>\n\t<proxies>\n\t\t<proxy>\n\t\t\t<id>NetFree</id>\n\t\t\t<active>true</active>\n\t\t\t<protocol>http</protocol>\n\t\t\t<host>$1</host>\n\t\t\t<port>8080</port>\n\t\t</proxy>\n\t</proxies>\n</settings>"
		echo -e $prox_mvn > .m2/settings.xml && cat .m2/settings.xml
	fi
}
if [[ "$(id -u)" != "0" ]];then
	echo "Requer root"
else
	if [[ "$1" == "-d" ]];then
		rm -rf /etc/apt/apt.conf $HOME/.m2/settings.xml
	else
		proxy_apt $*
		proxy_mvn $* 
	fi
fi

