#!/bin/bash

proxy_apt(){
	prox_apt="Acquire::http::Proxy"''' "http://192.168.'''$1''':8080";'''
	echo $prox_apt > /etc/apt/apt.conf && cat /etc/apt/apt.conf
}
proxy_mvn(){
	prox_mvn="<settings>\n\t<proxies>\n\t\t<proxy>\n\t\t\t<id>NetFree</id>\n\t\t\t<active>true</active>\n\t\t\t<protocol>http</protocol>\n\t\t\t<host>192.168.$1</host>\n\t\t\t<port>8080</port>\n\t\t</proxy>\n\t</proxies>\n</settings>"
	echo -e $prox_mvn > .m2/settings.xml && cat .m2/settings.xml
}
if [[ "$(id -u)" != "0" ]];then
	echo "Requer root"
else
	if [[ "$1" == "-d" ]];then
		rm -rf /etc/apt/apt.conf .m2/settings.xml
	else
		proxy_apt $*
		proxy_mvn $* 
	fi
fi
